const museumData = {
    config: {
        common: { free: 1, locked: 2, priceMoney: 1000000, priceShards: 400 },
        uncommon: { free: 1, locked: 2, priceMoney: 5000000, priceShards: 800 },
        rare: { free: 1, locked: 2, priceMoney: 10000000, priceShards: 1500 },
        epic: { free: 1, locked: 2, priceMoney: 100000000, priceShards: 2250 },
        legendary: { free: 1, locked: 2, priceMoney: 1000000000, priceShards: 3000 },
        mythic: { free: 0, locked: 2, priceMoney: 10000000000, priceShards: 5000 },
        exotic: { free: 0, locked: 1, priceMoney: null, priceShards: 10000 }
    },
    ores: {
        "Aetherite": { minKG: 20, value: 4444444, stats: { "Dig Speed": 0.3 } },
        "Amber": { minKG: 21, value: 110000, stats: { "Sell Boost": 0.13 } },
        "Amethyst": { minKG: 16, value: 3500, stats: { "Dig Speed": 0.05 } },
        "Ammonite Fossil": { minKG: 49, value: 200000, stats: { "Capacity": 0.2 } },
        "Aquamarine": { minKG: 20, value: 4000000, stats: { "Dig Speed": 0.3 } },
        "Ashvein": { minKG: 20, value: 222000, stats: { "Size Boost": 0.14 } },
        "Astral Spore": { minKG: 20, value: 400000000, stats: { "Dig Speed": 0.8 } },
        "Aurorite": { minKG: 30, value: 444444, stats: { "Dig Speed": 0.2 } },
        "Azuralite": { minKG: 30, value: 120000, stats: { "Dig Speed": 0.13 } },
        "Bismuth": { minKG: 78, value: 2600000, stats: { "Dig Speed": 0.3 } },
        "Bloodstone": { minKG: 40, value: 250000000, stats: { "Size Boost": 0.56 } },
        "Blue Ice": { minKG: 39, value: 1500, stats: { "Dig Speed": 0.05 } },
        "Bone": { minKG: 47, value: 200000, stats: { "Size Boost": 0.14 } },
        "Borealite": { minKG: 20, value: 280000, stats: { "Dig Speed": 0.2 } },
        "Catseye": { minKG: 20, value: 2222222, stats: { "Capacity": 0.3 } },
        "Chrysoberyl": { minKG: 21, value: 21000000, stats: { "Luck": 0.5 } },
        "Cinnabar": { minKG: 20, value: 900000, stats: { "Size Boost": 0.21 } },
        "Cobalt": { minKG: 38, value: 250000, stats: { "Dig Speed": 0.2 } },
        "Copper": { minKG: 60, value: 800, stats: { "Size Boost": 0.04 } },
        "Coral": { minKG: 10, value: 23000, stats: { "Capacity": 0.08 } },
        "Cryonic Artifact": { minKG: 20, value: 100000000, stats: { "Dig Strength": 1.2, "Shake Strength": 1.2, "Dig Speed": -0.8, "Shake Speed": -0.8 } },
        "Diamond": { minKG: 20, value: 1000000, stats: { "Luck": 0.3 } },
        "Dinosaur Skull": { minKG: 100, value: 50000000, stats: { "Sell Boost": 0.4, "Size Boost": 0.32 } },
        "Diopside": { minKG: 21, value: 99000, stats: { "Modifier Boost": 0.13 } },
        "Dragon Bone": { minKG: 50, value: 2000000, stats: { "Size Boost": 0.21 } },
        "Electrum": { minKG: 40, value: 13000, stats: { "Sell Boost": 0.08 } },
        "Emerald": { minKG: 20, value: 250000, stats: { "Luck": 0.2 } },
        "Fire Opal": { minKG: 20, value: 1600000, stats: { "Size Boost": 0.21 } },
        "Firefly Stone": { minKG: 60, value: 1500000, stats: { "Capacity": 0.3 } },
        "Flarebloom": { minKG: 21, value: 30000000, stats: { "Luck": 0.75, "Size Boost": -0.5 } },
        "Frostshard": { minKG: 20, value: 50000000, stats: { "Dig Strength": 0.5 } },
        "Glacial Quartz": { minKG: 42, value: 100000, stats: { "Dig Speed": 0.13 } },
        "Gloomberry": { minKG: 40, value: 80000, stats: { "Dig Speed": 0.13 } },
        "Gloomcap": { minKG: 20, value: 2340000, stats: { "Dig Speed": 0.3 } },
        "Glowberry": { minKG: 40, value: 12000, stats: { "Sell Boost": 0.08 } },
        "Glowmoss": { minKG: 60, value: 175000, stats: { "Modifier Boost": 0.2 } },
        "Gold": { minKG: 20, value: 1000, stats: { "Sell Boost": 0.05 } },
        "Golden Pearl": { minKG: 19, value: 250000, stats: { "Capacity": 0.2 } },
        "Inferlume": { minKG: 20, value: 14000000, stats: { "Luck": 0.5 } },
        "Iridium": { minKG: 40, value: 155000, stats: { "Dig Speed": 0.2 } },
        "Jade": { minKG: 40, value: 40000, stats: { "Modifier Boost": 0.13 } },
        "Lapis Lazuli": { minKG: 32, value: 40000, stats: { "Dig Speed": 0.13 } },
        "Lightshard": { minKG: 20, value: 300000, stats: { "Dig Speed": 0.2 } },
        "Lost Soul": { minKG: 20, value: 6666666, stats: { "Dig Speed": 0.3 } },
        "Luminum": { minKG: 40, value: 1500000, stats: { "Capacity": 0.3 } },
        "Malachite": { minKG: 18, value: 18000, stats: { "Modifier Boost": 0.08 } },
        "Mercury": { minKG: 76, value: 450000, stats: { "Shake Strength": 0.2 } },
        "Meteoric Iron": { minKG: 40, value: 80000, stats: { "Shake Strength": 0.13 } },
        "Moonstone": { minKG: 48, value: 200000, stats: { "Shake Speed": 0.2 } },
        "Mythril": { minKG: 60, value: 20000000, stats: { "Shake Strength": 0.5 } },
        "Neodymium": { minKG: 40, value: 10000, stats: { "Shake Strength": 0.08 } },
        "Obsidian": { minKG: 30, value: 3000, stats: { "Size Boost": 0.04 } },
        "Onyx": { minKG: 32, value: 75000, stats: { "Modifier Boost": 0.13 } },
        "Opal": { minKG: 20, value: 325000, stats: { "Shake Speed": 0.2 } },
        "Osmium": { minKG: 80, value: 300000, stats: { "Size Boost": 0.2 } },
        "Painite": { minKG: 20, value: 10000000, stats: { "Size Boost": 0.35 } },
        "Palladium": { minKG: 40, value: 500000, stats: { "Sell Boost": 0.3 } },
        "Pearl": { minKG: 19, value: 5000, stats: { "Shake Speed": 0.05 } },
        "Peridot": { minKG: 20, value: 60000, stats: { "Luck": 0.13 } },
        "Pink Diamond": { minKG: 20, value: 6000000, stats: { "Luck": 0.5 } },
        "Platinum": { minKG: 32, value: 2000, stats: { "Dig Speed": 0.05 } },
        "Prismara": { minKG: 20, value: 25000000, stats: { "Luck": 0.25, "Capacity": 0.25, "Dig Strength": 0.25, "Shake Strength": 0.25 } },
        "Pumpkin Soul": { minKG: 40, value: 40000000, stats: { "Size Boost": 0.56 } },
        "Pyrelith": { minKG: 30, value: 150000, stats: { "Sell Boost": 0.13 } },
        "Pyrite": { minKG: 55, value: 500, stats: { "Capacity": 0.05 } },
        "Pyronium": { minKG: 55, value: 226000, stats: { "Sell Boost": 0.2 } },
        "Radiant Gold": { minKG: 60, value: 40000000, stats: { "Sell Boost": 0.5 } },
        "Red Beryl": { minKG: 20, value: 28000000, stats: { "Size Boost": 0.35 } },
        "Rock Candy": { minKG: 45, value: 15000, stats: { "Size Boost": 0.05 } },
        "Rose Gold": { minKG: 40, value: 500000, stats: { "Shake Strength": 0.3 } },
        "Ruby": { minKG: 20, value: 30000, stats: { "Shake Strength": 0.13 } },
        "Sapphire": { minKG: 21, value: 25000, stats: { "Dig Speed": 0.08 } },
        "Seashell": { minKG: 19, value: 2200, stats: { "Capacity": 0.05 } },
        "Silver": { minKG: 36, value: 700, stats: { "Shake Speed": 0.05 } },
        "Silver Clamshell": { minKG: 21, value: 50000, stats: { "Shake Speed": 0.13 } },
        "Smoky Quartz": { minKG: 22, value: 16000, stats: { "Shake Strength": 0.08 } },
        "Specterite": { minKG: 10, value: 2800000, stats: { "Shake Speed": 0.3 } },
        "Star Garnet": { minKG: 20, value: 44000000, stats: { "Size Boost": 0.35 } },
        "Starshine": { minKG: 20, value: 2500000, stats: { "Dig Speed": 0.15, "Shake Speed": 0.15 } },
        "Titanium": { minKG: 40, value: 7500, stats: { "Dig Speed": 0.08 } },
        "Topaz": { minKG: 22, value: 14000, stats: { "Capacity": 0.08 } },
        "Tourmaline": { minKG: 25, value: 2888000, stats: { "Sell Boost": 0.3 } },
        "Umbrite": { minKG: 30, value: 180000000, stats: { "Dig Speed": 0.4, "Shake Speed": 0.4 } },
        "Uranium": { minKG: 59, value: 1500000, stats: { "Modifier Boost": 0.3 } },
        "Vineheart": { minKG: 40, value: 125000000, stats: { "Luck": 0.8 } },
        "Voidstone": { minKG: 20, value: 111111111, stats: { "Luck": 0.4, "Capacity": 0.4 } },
        "Volcanic Core": { minKG: 20, value: 40000000, stats: { "Dig Strength": 0.25, "Size Boost": 0.2 } },
        "Volcanic Key": { minKG: 20, value: 1500000, stats: { "Size Boost": 0.21 } },
        "Vortessence": { minKG: 20, value: 20000000, stats: { "Capacity": 0.5 } },
        "Zircon": { minKG: 15, value: 25000, stats: { "Size Boost": 0.05 } }
    },
    modifiers: {
        "None": { stats: {} },
        "Treasured": { stats: { "Luck": 0.0371 } }, // 13 / 350
        "Voidtorn": { stats: { "Luck": 0.0314, "Capacity": 0.0314 } }, // 11 / 350
        "Electrified": { stats: { "Dig Speed": 0.0143, "Shake Speed": 0.0143 } }, // 5 / 350
        "Iridescent": { stats: { "Luck": 0.01 } }, // 3.5 / 350
        "Crystalline": { stats: { "Size Boost": 0.0086 } }, // 3 / 350
        "Irradiated": { stats: { "Modifier Boost": 0.0071 } }, // 2.5 / 350
        "Scorching": { stats: { "Dig Strength": 0.0057 } }, // 2 / 350
        "Glowing": { stats: { "Shake Speed": 0.0046 } }, // 1.6 / 350
        "Pure": { stats: { "Dig Speed": 0.0039 } }, // 1.35 / 350
        "Shiny": { stats: { "Shake Strength": 0.0034 } } // 1.2 / 350
    },
    presets: {
        "Max Luck": {
            "common_0": { ore: "Gold", modifier: "Treasured", weight: 20 },
            "common_1": { ore: "Platinum", modifier: "Treasured", weight: 32 },
            "common_2": { ore: "Silver", modifier: "Treasured", weight: 36 },
            "uncommon_0": { ore: "Sapphire", modifier: "Treasured", weight: 21 },
            "uncommon_1": { ore: "Titanium", modifier: "Treasured", weight: 40 },
            "uncommon_2": { ore: "Topaz", modifier: "Treasured", weight: 22 },
            "rare_0": { ore: "Peridot", modifier: "Treasured", weight: 20 },
            "rare_1": { ore: "Amber", modifier: "Treasured", weight: 21 },
            "rare_2": { ore: "Pyrelith", modifier: "Treasured", weight: 30 },
            "epic_0": { ore: "Emerald", modifier: "Treasured", weight: 20 },
            "epic_1": { ore: "Lightshard", modifier: "Treasured", weight: 20 },
            "epic_2": { ore: "Opal", modifier: "Treasured", weight: 20 },
            "legendary_0": { ore: "Diamond", modifier: "Treasured", weight: 20 },
            "legendary_1": { ore: "Starshine", modifier: "Treasured", weight: 20 },
            "legendary_2": { ore: "Tourmaline", modifier: "Treasured", weight: 25 },
            "mythic_0": { ore: "Chrysoberyl", modifier: "Treasured", weight: 21 },
            "mythic_1": { ore: "Pink Diamond", modifier: "Treasured", weight: 20 },
            "exotic_0": { ore: "Vineheart", modifier: "Treasured", weight: 40 }
        },
        "Max Capacity": {
            "common_0": { ore: "Pyrite", modifier: "Voidtorn", weight: 55 },
            "common_1": { ore: "Seashell", modifier: "Voidtorn", weight: 19 },
            "common_2": { ore: "Pearl", modifier: "Voidtorn", weight: 19 },
            "uncommon_0": { ore: "Coral", modifier: "Voidtorn", weight: 10 },
            "uncommon_1": { ore: "Topaz", modifier: "Voidtorn", weight: 22 },
            "uncommon_2": { ore: "Rock Candy", modifier: "Voidtorn", weight: 45 },
            "rare_0": { ore: "Amber", modifier: "Voidtorn", weight: 21 },
            "rare_1": { ore: "Diopside", modifier: "Voidtorn", weight: 21 },
            "rare_2": { ore: "Silver Clamshell", modifier: "Voidtorn", weight: 21 },
            "epic_0": { ore: "Ammonite Fossil", modifier: "Voidtorn", weight: 49 },
            "epic_1": { ore: "Golden Pearl", modifier: "Voidtorn", weight: 19 },
            "epic_2": { ore: "Moonstone", modifier: "Voidtorn", weight: 48 },
            "legendary_0": { ore: "Catseye", modifier: "Voidtorn", weight: 20 },
            "legendary_1": { ore: "Firefly Stone", modifier: "Voidtorn", weight: 60 },
            "legendary_2": { ore: "Luminum", modifier: "Voidtorn", weight: 40 },
            "mythic_0": { ore: "Prismara", modifier: "Voidtorn", weight: 20 },
            "mythic_1": { ore: "Vortessence", modifier: "Voidtorn", weight: 20 },
            "exotic_0": { ore: "Voidstone", modifier: "Voidtorn", weight: 20 }
        },
        "Max Dig Speed": {
            "common_0": { ore: "Amethyst", modifier: "Electrified", weight: 16 },
            "common_1": { ore: "Blue Ice", modifier: "Electrified", weight: 39 },
            "common_2": { ore: "Platinum", modifier: "Electrified", weight: 32 },
            "uncommon_0": { ore: "Sapphire", modifier: "Electrified", weight: 21 },
            "uncommon_1": { ore: "Titanium", modifier: "Electrified", weight: 40 },
            "uncommon_2": { ore: "Topaz", modifier: "Electrified", weight: 22 },
            "rare_0": { ore: "Azuralite", modifier: "Electrified", weight: 30 },
            "rare_1": { ore: "Glacial Quartz", modifier: "Electrified", weight: 42 },
            "rare_2": { ore: "Lapis Lazuli", modifier: "Electrified", weight: 32 },
            "epic_0": { ore: "Aurorite", modifier: "Electrified", weight: 30 },
            "epic_1": { ore: "Borealite", modifier: "Electrified", weight: 20 },
            "epic_2": { ore: "Cobalt", modifier: "Electrified", weight: 38 },
            "legendary_0": { ore: "Aetherite", modifier: "Electrified", weight: 20 },
            "legendary_1": { ore: "Aquamarine", modifier: "Electrified", weight: 20 },
            "legendary_2": { ore: "Lost Soul", modifier: "Electrified", weight: 20 },
            "mythic_0": { ore: "Inferlume", modifier: "Electrified", weight: 20 },
            "mythic_1": { ore: "Pink Diamond", modifier: "Electrified", weight: 20 },
            "exotic_0": { ore: "Umbrite", modifier: "Electrified", weight: 30 }
        },
        "Max Sell Boost": {
            "common_0": { ore: "Gold", modifier: "None", weight: 20 },
            "common_1": { ore: "Platinum", modifier: "None", weight: 32 },
            "common_2": { ore: "Silver", modifier: "None", weight: 36 },
            "uncommon_0": { ore: "Electrum", modifier: "None", weight: 40 },
            "uncommon_1": { ore: "Glowberry", modifier: "None", weight: 40 },
            "uncommon_2": { ore: "Sapphire", modifier: "None", weight: 21 },
            "rare_0": { ore: "Amber", modifier: "None", weight: 21 },
            "rare_1": { ore: "Pyrelith", modifier: "None", weight: 30 },
            "rare_2": { ore: "Lapis Lazuli", modifier: "None", weight: 32 },
            "epic_0": { ore: "Pyronium", modifier: "None", weight: 55 },
            "epic_1": { ore: "Ashvein", modifier: "None", weight: 20 },
            "epic_2": { ore: "Borealite", modifier: "None", weight: 20 },
            "legendary_0": { ore: "Palladium", modifier: "None", weight: 40 },
            "legendary_1": { ore: "Tourmaline", modifier: "None", weight: 25 },
            "legendary_2": { ore: "Aquamarine", modifier: "None", weight: 20 },
            "mythic_0": { ore: "Radiant Gold", modifier: "None", weight: 60 },
            "mythic_1": { ore: "Pink Diamond", modifier: "None", weight: 20 },
            "exotic_0": { ore: "Dinosaur Skull", modifier: "None", weight: 100 }
        },
        "Balanced (All Stats)": {
            "common_0": { ore: "Gold", modifier: "Treasured", weight: 20 },
            "common_1": { ore: "Amethyst", modifier: "Electrified", weight: 16 },
            "common_2": { ore: "Pyrite", modifier: "Voidtorn", weight: 55 },
            "uncommon_0": { ore: "Sapphire", modifier: "Electrified", weight: 21 },
            "uncommon_1": { ore: "Titanium", modifier: "Electrified", weight: 40 },
            "uncommon_2": { ore: "Topaz", modifier: "Voidtorn", weight: 22 },
            "rare_0": { ore: "Peridot", modifier: "Treasured", weight: 20 },
            "rare_1": { ore: "Azuralite", modifier: "Electrified", weight: 30 },
            "rare_2": { ore: "Silver Clamshell", modifier: "Voidtorn", weight: 21 },
            "epic_0": { ore: "Emerald", modifier: "Treasured", weight: 20 },
            "epic_1": { ore: "Cobalt", modifier: "Electrified", weight: 38 },
            "epic_2": { ore: "Ammonite Fossil", modifier: "Voidtorn", weight: 49 },
            "legendary_0": { ore: "Diamond", modifier: "Treasured", weight: 20 },
            "legendary_1": { ore: "Aetherite", modifier: "Electrified", weight: 20 },
            "legendary_2": { ore: "Catseye", modifier: "Voidtorn", weight: 20 },
            "mythic_0": { ore: "Prismara", modifier: "Treasured", weight: 20 },
            "mythic_1": { ore: "Vortessence", modifier: "Voidtorn", weight: 20 },
            "exotic_0": { ore: "Vineheart", modifier: "Treasured", weight: 40 }
        },
        "Luck & Capacity": {
            "common_0": { ore: "Gold", modifier: "Voidtorn", weight: 20 },
            "common_1": { ore: "Pyrite", modifier: "Treasured", weight: 55 },
            "common_2": { ore: "Seashell", modifier: "Treasured", weight: 19 },
            "uncommon_0": { ore: "Coral", modifier: "Treasured", weight: 10 },
            "uncommon_1": { ore: "Topaz", modifier: "Voidtorn", weight: 22 },
            "uncommon_2": { ore: "Sapphire", modifier: "Treasured", weight: 21 },
            "rare_0": { ore: "Peridot", modifier: "Voidtorn", weight: 20 },
            "rare_1": { ore: "Amber", modifier: "Treasured", weight: 21 },
            "rare_2": { ore: "Silver Clamshell", modifier: "Voidtorn", weight: 21 },
            "epic_0": { ore: "Emerald", modifier: "Voidtorn", weight: 20 },
            "epic_1": { ore: "Ammonite Fossil", modifier: "Treasured", weight: 49 },
            "epic_2": { ore: "Golden Pearl", modifier: "Treasured", weight: 19 },
            "legendary_0": { ore: "Diamond", modifier: "Voidtorn", weight: 20 },
            "legendary_1": { ore: "Catseye", modifier: "Treasured", weight: 20 },
            "legendary_2": { ore: "Firefly Stone", modifier: "Voidtorn", weight: 60 },
            "mythic_0": { ore: "Prismara", modifier: "Voidtorn", weight: 20 },
            "mythic_1": { ore: "Vortessence", modifier: "Treasured", weight: 20 },
            "exotic_0": { ore: "Voidstone", modifier: "Voidtorn", weight: 20 }
        },
        "Speed (Dig & Shake)": {
            "common_0": { ore: "Amethyst", modifier: "Electrified", weight: 16 },
            "common_1": { ore: "Pearl", modifier: "Electrified", weight: 19 },
            "common_2": { ore: "Silver", modifier: "Electrified", weight: 36 },
            "uncommon_0": { ore: "Sapphire", modifier: "Electrified", weight: 21 },
            "uncommon_1": { ore: "Titanium", modifier: "Electrified", weight: 40 },
            "uncommon_2": { ore: "Topaz", modifier: "Electrified", weight: 22 },
            "rare_0": { ore: "Azuralite", modifier: "Electrified", weight: 30 },
            "rare_1": { ore: "Glacial Quartz", modifier: "Electrified", weight: 42 },
            "rare_2": { ore: "Silver Clamshell", modifier: "Electrified", weight: 21 },
            "epic_0": { ore: "Borealite", modifier: "Electrified", weight: 20 },
            "epic_1": { ore: "Cobalt", modifier: "Electrified", weight: 38 },
            "epic_2": { ore: "Opal", modifier: "Electrified", weight: 20 },
            "legendary_0": { ore: "Aetherite", modifier: "Electrified", weight: 20 },
            "legendary_1": { ore: "Starshine", modifier: "Electrified", weight: 20 },
            "legendary_2": { ore: "Specterite", modifier: "Electrified", weight: 10 },
            "mythic_0": { ore: "Inferlume", modifier: "Electrified", weight: 20 },
            "mythic_1": { ore: "Pink Diamond", modifier: "Electrified", weight: 20 },
            "exotic_0": { ore: "Umbrite", modifier: "Electrified", weight: 30 }
        },
        "Size Boost": {
            "common_0": { ore: "Copper", modifier: "Crystalline", weight: 60 },
            "common_1": { ore: "Obsidian", modifier: "Crystalline", weight: 30 },
            "common_2": { ore: "Gold", modifier: "Crystalline", weight: 20 },
            "uncommon_0": { ore: "Zircon", modifier: "Crystalline", weight: 15 },
            "uncommon_1": { ore: "Rock Candy", modifier: "Crystalline", weight: 45 },
            "uncommon_2": { ore: "Sapphire", modifier: "Crystalline", weight: 21 },
            "rare_0": { ore: "Peridot", modifier: "Crystalline", weight: 20 },
            "rare_1": { ore: "Amber", modifier: "Crystalline", weight: 21 },
            "rare_2": { ore: "Pyrelith", modifier: "Crystalline", weight: 30 },
            "epic_0": { ore: "Osmium", modifier: "Crystalline", weight: 80 },
            "epic_1": { ore: "Ashvein", modifier: "Crystalline", weight: 20 },
            "epic_2": { ore: "Bone", modifier: "Crystalline", weight: 47 },
            "legendary_0": { ore: "Volcanic Key", modifier: "Crystalline", weight: 20 },
            "legendary_1": { ore: "Fire Opal", modifier: "Crystalline", weight: 20 },
            "legendary_2": { ore: "Dragon Bone", modifier: "Crystalline", weight: 50 },
            "mythic_0": { ore: "Painite", modifier: "Crystalline", weight: 20 },
            "mythic_1": { ore: "Star Garnet", modifier: "Crystalline", weight: 20 },
            "exotic_0": { ore: "Bloodstone", modifier: "Crystalline", weight: 40 }
        },
        "Strength (Dig & Shake)": {
            "common_0": { ore: "Copper", modifier: "Scorching", weight: 60 },
            "common_1": { ore: "Gold", modifier: "Scorching", weight: 20 },
            "common_2": { ore: "Silver", modifier: "Shiny", weight: 36 },
            "uncommon_0": { ore: "Neodymium", modifier: "Shiny", weight: 40 },
            "uncommon_1": { ore: "Smoky Quartz", modifier: "Shiny", weight: 22 },
            "uncommon_2": { ore: "Sapphire", modifier: "Scorching", weight: 21 },
            "rare_0": { ore: "Meteoric Iron", modifier: "Shiny", weight: 40 },
            "rare_1": { ore: "Ruby", modifier: "Shiny", weight: 20 },
            "rare_2": { ore: "Peridot", modifier: "Scorching", weight: 20 },
            "epic_0": { ore: "Mercury", modifier: "Shiny", weight: 76 },
            "epic_1": { ore: "Emerald", modifier: "Scorching", weight: 20 },
            "epic_2": { ore: "Lightshard", modifier: "Scorching", weight: 20 },
            "legendary_0": { ore: "Rose Gold", modifier: "Shiny", weight: 40 },
            "legendary_1": { ore: "Diamond", modifier: "Scorching", weight: 20 },
            "legendary_2": { ore: "Aquamarine", modifier: "Scorching", weight: 20 },
            "mythic_0": { ore: "Mythril", modifier: "Shiny", weight: 60 },
            "mythic_1": { ore: "Prismara", modifier: "Scorching", weight: 20 },
            "exotic_0": { ore: "Cryonic Artifact", modifier: "Scorching", weight: 20 }
        },
        "Modifier Boost": {
            "common_0": { ore: "Gold", modifier: "Irradiated", weight: 20 },
            "common_1": { ore: "Platinum", modifier: "Irradiated", weight: 32 },
            "common_2": { ore: "Silver", modifier: "Irradiated", weight: 36 },
            "uncommon_0": { ore: "Malachite", modifier: "Irradiated", weight: 18 },
            "uncommon_1": { ore: "Sapphire", modifier: "Irradiated", weight: 21 },
            "uncommon_2": { ore: "Titanium", modifier: "Irradiated", weight: 40 },
            "rare_0": { ore: "Jade", modifier: "Irradiated", weight: 40 },
            "rare_1": { ore: "Onyx", modifier: "Irradiated", weight: 32 },
            "rare_2": { ore: "Diopside", modifier: "Irradiated", weight: 21 },
            "epic_0": { ore: "Glowmoss", modifier: "Irradiated", weight: 60 },
            "epic_1": { ore: "Emerald", modifier: "Irradiated", weight: 20 },
            "epic_2": { ore: "Lightshard", modifier: "Irradiated", weight: 20 },
            "legendary_0": { ore: "Uranium", modifier: "Irradiated", weight: 59 },
            "legendary_1": { ore: "Diamond", modifier: "Irradiated", weight: 20 },
            "legendary_2": { ore: "Aquamarine", modifier: "Irradiated", weight: 20 },
            "mythic_0": { ore: "Prismara", modifier: "Irradiated", weight: 20 },
            "mythic_1": { ore: "Pink Diamond", modifier: "Irradiated", weight: 20 },
            "exotic_0": { ore: "Vineheart", modifier: "Irradiated", weight: 40 }
        }
    }
};

const MODIFIERS = {
    "Normal": 1,
    "Shiny": 1.2,
    "Pure": 1.35,
    "Glowing": 1.6,
    "Scorching": 2,
    "Irradiated": 2.5,
    "Electrified": 5,
    "Voidtorn": 11
};